name: security-pipeline

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  sast_semgrep:
    name: SAST (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Semgrep
        run: pip install semgrep
      - name: Run Semgrep (CI ruleset)
        run: semgrep ci --config p/ci

  trivy_fs:
    name: Trivy (FS: code/deps/IaC/config)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          scanners: 'vuln,secret,config,license'
      - name: Upload SARIF (Trivy FS)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  trivy_image:
    name: Trivy (Container Image)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t demoapp:latest -f containers/app/Dockerfile containers/app
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'demoapp:latest'
          format: 'sarif'
          output: 'trivy-image.sarif'
          ignore-unfixed: true
      - name: Upload SARIF (Trivy Image)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image.sarif'
